# Environment Settings
gpu_id: 1

# Model Settings
n_layers: 2
n_heads: 2
hidden_size: 64
inner_size: 256
hidden_dropout_prob: 0.2
attn_dropout_prob: 0.2
hidden_act: gelu
layer_norm_eps: 1.e-12
initializer_range: 0.02
loss_type: CE  # ['CE', 'BPR']

similarity_type: dot
cl_loss_type: infonce  # ['dcl', 'infonce']
cl_lambda: 0.1
aug_type1: random  # ['random', 'crop', 'mask', 'reorder']
aug_type2: null
tau: 1  # softmax
eta: 0.2   # crop
gamma: 0.3   # mask
beta: 0.2   # reorder

model_aug: true
aug_layer_type: single # [single, inter]
layer_drop_num: 1 # number of layers to drop
n_aug_layer: 3 # number of augmented layers
layer_drop_thres: -1
cl_type: same # [same, sasrec-static]
en_weight: 0.1 # weight of encoder complementing

# Data settings
MAX_ITEM_LIST_LENGTH: 20

# Training Settings
train_batch_size: 256
neg_sampling: null