from recbole.model.sequential_recommender.bert4rec import BERT4Rec
from recbole.model.sequential_recommender.caser import Caser
from recbole.model.sequential_recommender.cl4rec import CL4Rec
from recbole.model.sequential_recommender.coserec import CoSeRec
from recbole.model.sequential_recommender.din import DIN
from recbole.model.sequential_recommender.dien import DIEN
from recbole.model.sequential_recommender.duorec import DuoRec
from recbole.model.sequential_recommender.fdsa import FDSA
from recbole.model.sequential_recommender.fpmc import FPMC
from recbole.model.sequential_recommender.gcsan import GCSAN
from recbole.model.sequential_recommender.gru4rec import GRU4Rec
from recbole.model.sequential_recommender.gru4recf import GRU4RecF
from recbole.model.sequential_recommender.gru4reckg import GRU4RecKG
from recbole.model.sequential_recommender.ksr import KSR
from recbole.model.sequential_recommender.myrec import MyRec
from recbole.model.sequential_recommender.myrec2 import MyRec2
from recbole.model.sequential_recommender.myrec3 import MyRec3
from recbole.model.sequential_recommender.narm import NARM
from recbole.model.sequential_recommender.nextitnet import NextItNet
from recbole.model.sequential_recommender.s3rec import S3Rec
from recbole.model.sequential_recommender.sasrec import SASRec
from recbole.model.sequential_recommender.sasrecussl import SASRecUSSL
from recbole.model.sequential_recommender.sasrecmf import SASRecMF
from recbole.model.sequential_recommender.sasrecf import SASRecF
from recbole.model.sequential_recommender.srgnn import SRGNN
from recbole.model.sequential_recommender.stamp import STAMP
from recbole.model.sequential_recommender.transrec import TransRec
from recbole.model.sequential_recommender.mminforec import MMInfoRec
from recbole.model.sequential_recommender.iclrec import ICLRec
from recbole.model.sequential_recommender.srma import SRMA
from recbole.model.sequential_recommender.hgn import HGN
from recbole.model.sequential_recommender.contrarec import ContraRec
from recbole.model.sequential_recommender.sasrecp import SASRecP
from recbole.model.sequential_recommender.ecl import ECL
